// <auto-generated />
using System;
using GestaoProdutos.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoProdutos.Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230414102922_dbContexting")]
    partial class dbContexting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoProdutos.Domain.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FornecedorCodigo")
                        .HasColumnType("int");

                    b.Property<string>("FornecedorDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "993555727645154",
                            DataFabricacao = new DateTime(2022, 10, 7, 1, 27, 4, 569, DateTimeKind.Local).AddTicks(9823),
                            DataValidade = new DateTime(2023, 10, 30, 23, 17, 17, 731, DateTimeKind.Local).AddTicks(179),
                            Descricao = "Unbranded Wooden Shoes",
                            FornecedorCnpj = "723125300001",
                            FornecedorCodigo = 281,
                            FornecedorDescricao = "Runolfsson, Lesch and Casper",
                            Quantidade = 36,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "330743658172774",
                            DataFabricacao = new DateTime(2023, 2, 20, 4, 36, 4, 566, DateTimeKind.Local).AddTicks(6373),
                            DataValidade = new DateTime(2023, 8, 22, 14, 8, 20, 245, DateTimeKind.Local).AddTicks(402),
                            Descricao = "Generic Metal Table",
                            FornecedorCnpj = "420250670001",
                            FornecedorCodigo = 872,
                            FornecedorDescricao = "Dickinson - Walter",
                            Quantidade = 1,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "698712379330985",
                            DataFabricacao = new DateTime(2023, 3, 24, 2, 29, 6, 949, DateTimeKind.Local).AddTicks(6242),
                            DataValidade = new DateTime(2024, 2, 21, 5, 54, 41, 453, DateTimeKind.Local).AddTicks(4694),
                            Descricao = "Awesome Granite Keyboard",
                            FornecedorCnpj = "104033480001",
                            FornecedorCodigo = 336,
                            FornecedorDescricao = "Barton - Stark",
                            Quantidade = 4,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "129645006738731",
                            DataFabricacao = new DateTime(2023, 3, 26, 10, 9, 21, 511, DateTimeKind.Local).AddTicks(7035),
                            DataValidade = new DateTime(2024, 3, 4, 2, 42, 3, 850, DateTimeKind.Local).AddTicks(1541),
                            Descricao = "Incredible Steel Shoes",
                            FornecedorCnpj = "057655130001",
                            FornecedorCodigo = 1744,
                            FornecedorDescricao = "Carroll - Halvorson",
                            Quantidade = 27,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "737647225524408",
                            DataFabricacao = new DateTime(2022, 4, 28, 16, 45, 25, 224, DateTimeKind.Local).AddTicks(1128),
                            DataValidade = new DateTime(2023, 6, 26, 10, 32, 41, 763, DateTimeKind.Local).AddTicks(9734),
                            Descricao = "Tasty Steel Pants",
                            FornecedorCnpj = "598018510001",
                            FornecedorCodigo = 1269,
                            FornecedorDescricao = "Will, Nitzsche and Simonis",
                            Quantidade = 70,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "287218365031513",
                            DataFabricacao = new DateTime(2022, 12, 16, 13, 53, 31, 708, DateTimeKind.Local).AddTicks(5230),
                            DataValidade = new DateTime(2023, 12, 28, 20, 15, 40, 711, DateTimeKind.Local).AddTicks(2036),
                            Descricao = "Handmade Metal Cheese",
                            FornecedorCnpj = "588777890001",
                            FornecedorCodigo = 396,
                            FornecedorDescricao = "Ondricka - Becker",
                            Quantidade = 22,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "512549930500787",
                            DataFabricacao = new DateTime(2022, 12, 21, 17, 53, 17, 310, DateTimeKind.Local).AddTicks(9686),
                            DataValidade = new DateTime(2024, 3, 8, 13, 37, 40, 789, DateTimeKind.Local).AddTicks(5246),
                            Descricao = "Practical Frozen Shirt",
                            FornecedorCnpj = "851455670001",
                            FornecedorCodigo = 182,
                            FornecedorDescricao = "Kuvalis Group",
                            Quantidade = 38,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "681863830936189",
                            DataFabricacao = new DateTime(2022, 11, 14, 10, 24, 46, 524, DateTimeKind.Local).AddTicks(8640),
                            DataValidade = new DateTime(2024, 2, 15, 13, 2, 25, 735, DateTimeKind.Local).AddTicks(1290),
                            Descricao = "Fantastic Plastic Chips",
                            FornecedorCnpj = "363930250001",
                            FornecedorCodigo = 597,
                            FornecedorDescricao = "Little, Quitzon and Zulauf",
                            Quantidade = 75,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "592466729748171",
                            DataFabricacao = new DateTime(2022, 11, 7, 17, 6, 41, 577, DateTimeKind.Local).AddTicks(6981),
                            DataValidade = new DateTime(2023, 8, 17, 8, 42, 34, 650, DateTimeKind.Local).AddTicks(390),
                            Descricao = "Small Metal Bacon",
                            FornecedorCnpj = "929308270001",
                            FornecedorCodigo = 1709,
                            FornecedorDescricao = "Weber, Hyatt and Jones",
                            Quantidade = 38,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "648612223784112",
                            DataFabricacao = new DateTime(2022, 11, 6, 10, 38, 49, 524, DateTimeKind.Local).AddTicks(1886),
                            DataValidade = new DateTime(2023, 6, 30, 14, 39, 39, 9, DateTimeKind.Local).AddTicks(8360),
                            Descricao = "Licensed Wooden Table",
                            FornecedorCnpj = "292107550001",
                            FornecedorCodigo = 1611,
                            FornecedorDescricao = "Bergstrom, Ortiz and Kovacek",
                            Quantidade = 74,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "279007141252489",
                            DataFabricacao = new DateTime(2022, 8, 28, 1, 47, 44, 611, DateTimeKind.Local).AddTicks(9606),
                            DataValidade = new DateTime(2023, 4, 30, 17, 34, 28, 52, DateTimeKind.Local).AddTicks(8665),
                            Descricao = "Generic Cotton Pizza",
                            FornecedorCnpj = "763267250001",
                            FornecedorCodigo = 521,
                            FornecedorDescricao = "Walsh, Hessel and Schimmel",
                            Quantidade = 87,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "553655281459604",
                            DataFabricacao = new DateTime(2022, 7, 29, 2, 1, 0, 323, DateTimeKind.Local).AddTicks(8041),
                            DataValidade = new DateTime(2023, 12, 21, 22, 2, 33, 355, DateTimeKind.Local).AddTicks(2737),
                            Descricao = "Generic Wooden Fish",
                            FornecedorCnpj = "910713840001",
                            FornecedorCodigo = 653,
                            FornecedorDescricao = "Ritchie, Homenick and Howell",
                            Quantidade = 14,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "082082568730459",
                            DataFabricacao = new DateTime(2022, 9, 1, 21, 27, 33, 956, DateTimeKind.Local).AddTicks(9204),
                            DataValidade = new DateTime(2023, 7, 30, 2, 51, 45, 492, DateTimeKind.Local).AddTicks(9956),
                            Descricao = "Refined Cotton Computer",
                            FornecedorCnpj = "409646620001",
                            FornecedorCodigo = 1136,
                            FornecedorDescricao = "Morar, Hilll and Huels",
                            Quantidade = 32,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "399244193795951",
                            DataFabricacao = new DateTime(2023, 3, 3, 1, 14, 38, 74, DateTimeKind.Local).AddTicks(4345),
                            DataValidade = new DateTime(2023, 6, 16, 6, 18, 55, 460, DateTimeKind.Local).AddTicks(3581),
                            Descricao = "Intelligent Cotton Gloves",
                            FornecedorCnpj = "265132730001",
                            FornecedorCodigo = 1605,
                            FornecedorDescricao = "Huels - Simonis",
                            Quantidade = 6,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "943897652297639",
                            DataFabricacao = new DateTime(2022, 9, 30, 19, 2, 23, 140, DateTimeKind.Local).AddTicks(1447),
                            DataValidade = new DateTime(2023, 12, 18, 2, 26, 47, 168, DateTimeKind.Local).AddTicks(1493),
                            Descricao = "Practical Frozen Table",
                            FornecedorCnpj = "738978090001",
                            FornecedorCodigo = 1865,
                            FornecedorDescricao = "Hayes LLC",
                            Quantidade = 47,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "990470761456761",
                            DataFabricacao = new DateTime(2023, 2, 14, 4, 46, 4, 221, DateTimeKind.Local).AddTicks(9137),
                            DataValidade = new DateTime(2023, 10, 11, 2, 34, 26, 796, DateTimeKind.Local).AddTicks(6552),
                            Descricao = "Fantastic Granite Pants",
                            FornecedorCnpj = "055631550001",
                            FornecedorCodigo = 986,
                            FornecedorDescricao = "Doyle, Harber and Kovacek",
                            Quantidade = 33,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "123366926675384",
                            DataFabricacao = new DateTime(2022, 6, 8, 13, 22, 41, 250, DateTimeKind.Local).AddTicks(7267),
                            DataValidade = new DateTime(2023, 10, 3, 20, 3, 2, 376, DateTimeKind.Local).AddTicks(8174),
                            Descricao = "Intelligent Soft Computer",
                            FornecedorCnpj = "164810780001",
                            FornecedorCodigo = 942,
                            FornecedorDescricao = "Schiller LLC",
                            Quantidade = 71,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "152453120063282",
                            DataFabricacao = new DateTime(2022, 11, 17, 4, 25, 0, 2, DateTimeKind.Local).AddTicks(1400),
                            DataValidade = new DateTime(2023, 7, 20, 9, 57, 56, 516, DateTimeKind.Local).AddTicks(6514),
                            Descricao = "Awesome Plastic Soap",
                            FornecedorCnpj = "134043070001",
                            FornecedorCodigo = 88,
                            FornecedorDescricao = "Jacobson - Hintz",
                            Quantidade = 74,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "158340505449817",
                            DataFabricacao = new DateTime(2022, 7, 25, 4, 53, 41, 384, DateTimeKind.Local).AddTicks(7288),
                            DataValidade = new DateTime(2023, 9, 24, 13, 47, 20, 286, DateTimeKind.Local).AddTicks(1322),
                            Descricao = "Handmade Concrete Chair",
                            FornecedorCnpj = "692354980001",
                            FornecedorCodigo = 417,
                            FornecedorDescricao = "Kovacek, Homenick and Connelly",
                            Quantidade = 44,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "095512257076044",
                            DataFabricacao = new DateTime(2022, 5, 1, 14, 32, 41, 768, DateTimeKind.Local).AddTicks(6557),
                            DataValidade = new DateTime(2024, 2, 22, 17, 10, 35, 339, DateTimeKind.Local).AddTicks(9152),
                            Descricao = "Refined Metal Salad",
                            FornecedorCnpj = "854064970001",
                            FornecedorCodigo = 728,
                            FornecedorDescricao = "Hegmann - Shanahan",
                            Quantidade = 23,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "551461840072022",
                            DataFabricacao = new DateTime(2023, 2, 1, 21, 19, 32, 250, DateTimeKind.Local).AddTicks(7545),
                            DataValidade = new DateTime(2023, 5, 19, 6, 2, 16, 372, DateTimeKind.Local).AddTicks(3734),
                            Descricao = "Awesome Concrete Chicken",
                            FornecedorCnpj = "199881950001",
                            FornecedorCodigo = 794,
                            FornecedorDescricao = "Nicolas, Leffler and Fisher",
                            Quantidade = 94,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "827326580391060",
                            DataFabricacao = new DateTime(2022, 10, 5, 12, 59, 9, 510, DateTimeKind.Local).AddTicks(714),
                            DataValidade = new DateTime(2023, 12, 7, 16, 3, 10, 762, DateTimeKind.Local).AddTicks(7674),
                            Descricao = "Sleek Plastic Pants",
                            FornecedorCnpj = "389258230001",
                            FornecedorCodigo = 1102,
                            FornecedorDescricao = "Mosciski Inc",
                            Quantidade = 73,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "177188313166446",
                            DataFabricacao = new DateTime(2022, 7, 26, 3, 43, 9, 156, DateTimeKind.Local).AddTicks(5769),
                            DataValidade = new DateTime(2023, 12, 31, 14, 58, 59, 958, DateTimeKind.Local).AddTicks(96),
                            Descricao = "Awesome Fresh Chair",
                            FornecedorCnpj = "501164740001",
                            FornecedorCodigo = 634,
                            FornecedorDescricao = "Parisian, Strosin and Smith",
                            Quantidade = 56,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "716504950322807",
                            DataFabricacao = new DateTime(2022, 11, 19, 18, 46, 27, 673, DateTimeKind.Local).AddTicks(7214),
                            DataValidade = new DateTime(2024, 3, 17, 12, 44, 13, 385, DateTimeKind.Local).AddTicks(5382),
                            Descricao = "Ergonomic Cotton Cheese",
                            FornecedorCnpj = "532665660001",
                            FornecedorCodigo = 839,
                            FornecedorDescricao = "Homenick LLC",
                            Quantidade = 87,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "807655248463906",
                            DataFabricacao = new DateTime(2022, 7, 29, 3, 20, 23, 647, DateTimeKind.Local).AddTicks(677),
                            DataValidade = new DateTime(2023, 10, 21, 14, 48, 33, 67, DateTimeKind.Local).AddTicks(1794),
                            Descricao = "Rustic Metal Bacon",
                            FornecedorCnpj = "676320970001",
                            FornecedorCodigo = 95,
                            FornecedorDescricao = "Schaden - Feil",
                            Quantidade = 68,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "137113688747715",
                            DataFabricacao = new DateTime(2022, 4, 27, 5, 22, 19, 537, DateTimeKind.Local).AddTicks(5112),
                            DataValidade = new DateTime(2023, 5, 27, 4, 10, 59, 322, DateTimeKind.Local).AddTicks(2261),
                            Descricao = "Gorgeous Plastic Hat",
                            FornecedorCnpj = "141749930001",
                            FornecedorCodigo = 381,
                            FornecedorDescricao = "Klocko Inc",
                            Quantidade = 17,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "034169802256391",
                            DataFabricacao = new DateTime(2023, 2, 20, 11, 11, 58, 991, DateTimeKind.Local).AddTicks(5794),
                            DataValidade = new DateTime(2024, 2, 20, 1, 49, 53, 744, DateTimeKind.Local).AddTicks(8370),
                            Descricao = "Practical Granite Pizza",
                            FornecedorCnpj = "437528100001",
                            FornecedorCodigo = 638,
                            FornecedorDescricao = "Lehner - Davis",
                            Quantidade = 25,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "116368652642978",
                            DataFabricacao = new DateTime(2023, 2, 4, 18, 42, 49, 664, DateTimeKind.Local).AddTicks(1659),
                            DataValidade = new DateTime(2023, 6, 2, 17, 51, 32, 713, DateTimeKind.Local).AddTicks(1749),
                            Descricao = "Handcrafted Fresh Gloves",
                            FornecedorCnpj = "052116570001",
                            FornecedorCodigo = 1310,
                            FornecedorDescricao = "Toy - Armstrong",
                            Quantidade = 61,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "354007764326816",
                            DataFabricacao = new DateTime(2022, 11, 25, 10, 43, 11, 724, DateTimeKind.Local).AddTicks(7587),
                            DataValidade = new DateTime(2023, 11, 6, 21, 18, 5, 378, DateTimeKind.Local).AddTicks(2381),
                            Descricao = "Sleek Soft Pants",
                            FornecedorCnpj = "942194160001",
                            FornecedorCodigo = 1346,
                            FornecedorDescricao = "Aufderhar LLC",
                            Quantidade = 72,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "042319924302634",
                            DataFabricacao = new DateTime(2022, 8, 9, 3, 40, 50, 654, DateTimeKind.Local).AddTicks(6252),
                            DataValidade = new DateTime(2024, 2, 20, 8, 41, 45, 749, DateTimeKind.Local).AddTicks(4598),
                            Descricao = "Licensed Cotton Cheese",
                            FornecedorCnpj = "443382120001",
                            FornecedorCodigo = 1064,
                            FornecedorDescricao = "Feil Group",
                            Quantidade = 25,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 31,
                            Codigo = "378045293182570",
                            DataFabricacao = new DateTime(2023, 2, 28, 3, 19, 14, 412, DateTimeKind.Local).AddTicks(2511),
                            DataValidade = new DateTime(2023, 9, 8, 2, 19, 27, 781, DateTimeKind.Local).AddTicks(8719),
                            Descricao = "Rustic Wooden Chips",
                            FornecedorCnpj = "578616920001",
                            FornecedorCodigo = 1278,
                            FornecedorDescricao = "Hudson, Hammes and Mraz",
                            Quantidade = 49,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 32,
                            Codigo = "259986346512308",
                            DataFabricacao = new DateTime(2023, 2, 15, 1, 28, 48, 556, DateTimeKind.Local).AddTicks(576),
                            DataValidade = new DateTime(2023, 7, 30, 19, 20, 14, 421, DateTimeKind.Local).AddTicks(7018),
                            Descricao = "Handcrafted Soft Towels",
                            FornecedorCnpj = "053806810001",
                            FornecedorCodigo = 1081,
                            FornecedorDescricao = "Hessel - Toy",
                            Quantidade = 59,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 33,
                            Codigo = "329292738685831",
                            DataFabricacao = new DateTime(2023, 2, 18, 2, 24, 45, 787, DateTimeKind.Local).AddTicks(9859),
                            DataValidade = new DateTime(2023, 9, 22, 21, 49, 14, 216, DateTimeKind.Local).AddTicks(6043),
                            Descricao = "Awesome Metal Mouse",
                            FornecedorCnpj = "988919590001",
                            FornecedorCodigo = 393,
                            FornecedorDescricao = "Rowe, Lubowitz and Hackett",
                            Quantidade = 67,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 34,
                            Codigo = "375422138035402",
                            DataFabricacao = new DateTime(2022, 10, 24, 15, 40, 39, 873, DateTimeKind.Local).AddTicks(7489),
                            DataValidade = new DateTime(2023, 5, 30, 3, 2, 0, 353, DateTimeKind.Local).AddTicks(3872),
                            Descricao = "Generic Frozen Mouse",
                            FornecedorCnpj = "232702620001",
                            FornecedorCodigo = 749,
                            FornecedorDescricao = "Ryan, Grady and Sporer",
                            Quantidade = 30,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 35,
                            Codigo = "624937287554812",
                            DataFabricacao = new DateTime(2022, 8, 5, 23, 30, 16, 807, DateTimeKind.Local).AddTicks(287),
                            DataValidade = new DateTime(2024, 2, 4, 1, 32, 55, 379, DateTimeKind.Local).AddTicks(7586),
                            Descricao = "Gorgeous Wooden Chicken",
                            FornecedorCnpj = "491721870001",
                            FornecedorCodigo = 598,
                            FornecedorDescricao = "Aufderhar - Schiller",
                            Quantidade = 10,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 36,
                            Codigo = "590181778388351",
                            DataFabricacao = new DateTime(2022, 7, 11, 18, 47, 29, 61, DateTimeKind.Local).AddTicks(8679),
                            DataValidade = new DateTime(2023, 8, 18, 9, 9, 38, 552, DateTimeKind.Local).AddTicks(9213),
                            Descricao = "Fantastic Frozen Chips",
                            FornecedorCnpj = "324990210001",
                            FornecedorCodigo = 468,
                            FornecedorDescricao = "Feest - Bauch",
                            Quantidade = 16,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 37,
                            Codigo = "698134962701406",
                            DataFabricacao = new DateTime(2023, 2, 20, 11, 58, 57, 831, DateTimeKind.Local).AddTicks(3803),
                            DataValidade = new DateTime(2023, 10, 3, 13, 35, 27, 752, DateTimeKind.Local).AddTicks(4686),
                            Descricao = "Refined Cotton Soap",
                            FornecedorCnpj = "179079480001",
                            FornecedorCodigo = 1583,
                            FornecedorDescricao = "Ebert - Wolff",
                            Quantidade = 45,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 38,
                            Codigo = "674644887010882",
                            DataFabricacao = new DateTime(2023, 4, 3, 8, 21, 57, 947, DateTimeKind.Local).AddTicks(2138),
                            DataValidade = new DateTime(2023, 11, 4, 22, 25, 50, 885, DateTimeKind.Local).AddTicks(1632),
                            Descricao = "Fantastic Concrete Salad",
                            FornecedorCnpj = "949471510001",
                            FornecedorCodigo = 201,
                            FornecedorDescricao = "Parisian LLC",
                            Quantidade = 22,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 39,
                            Codigo = "477405473646258",
                            DataFabricacao = new DateTime(2022, 12, 14, 2, 50, 17, 287, DateTimeKind.Local).AddTicks(45),
                            DataValidade = new DateTime(2024, 1, 24, 2, 58, 8, 767, DateTimeKind.Local).AddTicks(3137),
                            Descricao = "Awesome Soft Pants",
                            FornecedorCnpj = "884206120001",
                            FornecedorCodigo = 1841,
                            FornecedorDescricao = "Borer Group",
                            Quantidade = 30,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 40,
                            Codigo = "748491822068104",
                            DataFabricacao = new DateTime(2022, 5, 18, 6, 36, 20, 316, DateTimeKind.Local).AddTicks(1710),
                            DataValidade = new DateTime(2024, 1, 18, 14, 4, 51, 292, DateTimeKind.Local).AddTicks(9513),
                            Descricao = "Handcrafted Frozen Towels",
                            FornecedorCnpj = "079848830001",
                            FornecedorCodigo = 254,
                            FornecedorDescricao = "Blanda, Nitzsche and Reichert",
                            Quantidade = 94,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 41,
                            Codigo = "034080033987564",
                            DataFabricacao = new DateTime(2022, 6, 29, 15, 29, 16, 101, DateTimeKind.Local).AddTicks(5528),
                            DataValidade = new DateTime(2023, 10, 1, 11, 29, 53, 478, DateTimeKind.Local).AddTicks(8701),
                            Descricao = "Tasty Fresh Salad",
                            FornecedorCnpj = "267213020001",
                            FornecedorCodigo = 1621,
                            FornecedorDescricao = "Wuckert, Abbott and Wintheiser",
                            Quantidade = 7,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 42,
                            Codigo = "429316086576195",
                            DataFabricacao = new DateTime(2022, 6, 29, 22, 59, 14, 658, DateTimeKind.Local).AddTicks(7142),
                            DataValidade = new DateTime(2023, 9, 15, 4, 56, 57, 80, DateTimeKind.Local).AddTicks(1538),
                            Descricao = "Sleek Frozen Computer",
                            FornecedorCnpj = "877218030001",
                            FornecedorCodigo = 1341,
                            FornecedorDescricao = "Emard Group",
                            Quantidade = 94,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 43,
                            Codigo = "066651777729280",
                            DataFabricacao = new DateTime(2022, 5, 14, 23, 59, 18, 771, DateTimeKind.Local).AddTicks(4519),
                            DataValidade = new DateTime(2024, 1, 2, 9, 4, 18, 884, DateTimeKind.Local).AddTicks(8545),
                            Descricao = "Tasty Metal Fish",
                            FornecedorCnpj = "942220250001",
                            FornecedorCodigo = 1328,
                            FornecedorDescricao = "Morissette Group",
                            Quantidade = 48,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 44,
                            Codigo = "914633283564975",
                            DataFabricacao = new DateTime(2022, 10, 2, 22, 21, 16, 875, DateTimeKind.Local).AddTicks(8573),
                            DataValidade = new DateTime(2024, 4, 8, 18, 3, 19, 669, DateTimeKind.Local).AddTicks(8256),
                            Descricao = "Small Cotton Hat",
                            FornecedorCnpj = "198433650001",
                            FornecedorCodigo = 348,
                            FornecedorDescricao = "Murray, Goldner and Breitenberg",
                            Quantidade = 70,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 45,
                            Codigo = "463397556152027",
                            DataFabricacao = new DateTime(2022, 6, 7, 13, 7, 48, 696, DateTimeKind.Local).AddTicks(3873),
                            DataValidade = new DateTime(2023, 8, 20, 5, 37, 10, 780, DateTimeKind.Local).AddTicks(6552),
                            Descricao = "Handcrafted Steel Shirt",
                            FornecedorCnpj = "113723100001",
                            FornecedorCodigo = 1488,
                            FornecedorDescricao = "Yundt - Keeling",
                            Quantidade = 87,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 46,
                            Codigo = "681125193278798",
                            DataFabricacao = new DateTime(2023, 1, 22, 12, 32, 2, 230, DateTimeKind.Local).AddTicks(7501),
                            DataValidade = new DateTime(2024, 3, 31, 15, 53, 10, 603, DateTimeKind.Local).AddTicks(8471),
                            Descricao = "Handcrafted Plastic Chair",
                            FornecedorCnpj = "677568460001",
                            FornecedorCodigo = 1015,
                            FornecedorDescricao = "Hoppe, Zulauf and Lind",
                            Quantidade = 96,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 47,
                            Codigo = "765538624248520",
                            DataFabricacao = new DateTime(2022, 10, 24, 4, 0, 14, 506, DateTimeKind.Local).AddTicks(4310),
                            DataValidade = new DateTime(2023, 11, 6, 20, 8, 37, 763, DateTimeKind.Local).AddTicks(5018),
                            Descricao = "Small Concrete Chips",
                            FornecedorCnpj = "954807740001",
                            FornecedorCodigo = 853,
                            FornecedorDescricao = "Beier - Hegmann",
                            Quantidade = 84,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 48,
                            Codigo = "993094619721575",
                            DataFabricacao = new DateTime(2022, 8, 24, 4, 47, 7, 940, DateTimeKind.Local).AddTicks(3006),
                            DataValidade = new DateTime(2024, 2, 18, 11, 9, 18, 574, DateTimeKind.Local).AddTicks(7739),
                            Descricao = "Small Plastic Towels",
                            FornecedorCnpj = "956716470001",
                            FornecedorCodigo = 240,
                            FornecedorDescricao = "DuBuque - Schimmel",
                            Quantidade = 67,
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 49,
                            Codigo = "492571765965468",
                            DataFabricacao = new DateTime(2023, 2, 3, 21, 51, 39, 675, DateTimeKind.Local).AddTicks(4691),
                            DataValidade = new DateTime(2023, 9, 25, 22, 44, 43, 996, DateTimeKind.Local).AddTicks(3944),
                            Descricao = "Incredible Cotton Keyboard",
                            FornecedorCnpj = "966851980001",
                            FornecedorCodigo = 1228,
                            FornecedorDescricao = "Prohaska, Nienow and Marquardt",
                            Quantidade = 89,
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 50,
                            Codigo = "488994852973323",
                            DataFabricacao = new DateTime(2022, 11, 6, 22, 48, 19, 677, DateTimeKind.Local).AddTicks(5982),
                            DataValidade = new DateTime(2023, 11, 27, 21, 17, 58, 166, DateTimeKind.Local).AddTicks(893),
                            Descricao = "Incredible Rubber Sausages",
                            FornecedorCnpj = "617458560001",
                            FornecedorCodigo = 486,
                            FornecedorDescricao = "Blick Inc",
                            Quantidade = 34,
                            Situacao = "Inativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
