// <auto-generated />
using System;
using GestaoProdutos.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoProdutos.Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoProdutos.Domain.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FornecedorCnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FornecedorCodigo")
                        .HasColumnType("int");

                    b.Property<string>("FornecedorDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "525814128898576",
                            DataFabricacao = new DateTime(2022, 9, 30, 12, 54, 13, 489, DateTimeKind.Local).AddTicks(5181),
                            DataValidade = new DateTime(2023, 9, 27, 2, 40, 4, 358, DateTimeKind.Local).AddTicks(7980),
                            Descricao = "Handcrafted Cotton Salad",
                            FornecedorCnpj = "447272390001",
                            FornecedorCodigo = 819,
                            FornecedorDescricao = "Hahn Inc",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "411914198066469",
                            DataFabricacao = new DateTime(2022, 10, 15, 18, 2, 13, 172, DateTimeKind.Local).AddTicks(1392),
                            DataValidade = new DateTime(2023, 11, 5, 22, 39, 2, 730, DateTimeKind.Local).AddTicks(774),
                            Descricao = "Rustic Plastic Computer",
                            FornecedorCnpj = "297432500001",
                            FornecedorCodigo = 289,
                            FornecedorDescricao = "Schultz, Pollich and Moen",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "634532717114483",
                            DataFabricacao = new DateTime(2023, 3, 8, 6, 18, 46, 940, DateTimeKind.Local).AddTicks(2560),
                            DataValidade = new DateTime(2023, 5, 3, 22, 37, 23, 734, DateTimeKind.Local).AddTicks(5333),
                            Descricao = "Awesome Rubber Chair",
                            FornecedorCnpj = "224392140001",
                            FornecedorCodigo = 1017,
                            FornecedorDescricao = "Frami - Hoppe",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "812064437132669",
                            DataFabricacao = new DateTime(2022, 9, 30, 22, 42, 37, 778, DateTimeKind.Local).AddTicks(951),
                            DataValidade = new DateTime(2023, 8, 22, 17, 11, 58, 729, DateTimeKind.Local).AddTicks(5898),
                            Descricao = "Unbranded Soft Tuna",
                            FornecedorCnpj = "253099040001",
                            FornecedorCodigo = 1025,
                            FornecedorDescricao = "Kulas and Sons",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "630955820030493",
                            DataFabricacao = new DateTime(2022, 12, 15, 0, 28, 55, 211, DateTimeKind.Local).AddTicks(2953),
                            DataValidade = new DateTime(2023, 11, 25, 21, 40, 4, 625, DateTimeKind.Local).AddTicks(491),
                            Descricao = "Practical Soft Table",
                            FornecedorCnpj = "666439230001",
                            FornecedorCodigo = 968,
                            FornecedorDescricao = "Sawayn - Lemke",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "213804402607931",
                            DataFabricacao = new DateTime(2022, 7, 3, 14, 35, 58, 229, DateTimeKind.Local).AddTicks(7276),
                            DataValidade = new DateTime(2024, 1, 22, 9, 19, 17, 398, DateTimeKind.Local).AddTicks(2852),
                            Descricao = "Refined Frozen Chips",
                            FornecedorCnpj = "933523320001",
                            FornecedorCodigo = 1223,
                            FornecedorDescricao = "Brakus and Sons",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "039227370969951",
                            DataFabricacao = new DateTime(2022, 6, 13, 14, 0, 31, 472, DateTimeKind.Local).AddTicks(6157),
                            DataValidade = new DateTime(2023, 12, 26, 12, 13, 10, 483, DateTimeKind.Local).AddTicks(8529),
                            Descricao = "Intelligent Plastic Shirt",
                            FornecedorCnpj = "598502640001",
                            FornecedorCodigo = 102,
                            FornecedorDescricao = "Prohaska, Kovacek and Kirlin",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "001737894175458",
                            DataFabricacao = new DateTime(2022, 11, 26, 8, 17, 17, 974, DateTimeKind.Local).AddTicks(9598),
                            DataValidade = new DateTime(2024, 3, 26, 14, 28, 48, 402, DateTimeKind.Local).AddTicks(9080),
                            Descricao = "Sleek Metal Fish",
                            FornecedorCnpj = "658014480001",
                            FornecedorCodigo = 1214,
                            FornecedorDescricao = "Rutherford - Schoen",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "381451100032066",
                            DataFabricacao = new DateTime(2022, 11, 24, 10, 45, 27, 279, DateTimeKind.Local).AddTicks(2477),
                            DataValidade = new DateTime(2024, 2, 19, 13, 54, 45, 600, DateTimeKind.Local).AddTicks(2179),
                            Descricao = "Practical Cotton Mouse",
                            FornecedorCnpj = "948653180001",
                            FornecedorCodigo = 219,
                            FornecedorDescricao = "Thompson, VonRueden and Glover",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "055897409836047",
                            DataFabricacao = new DateTime(2023, 1, 5, 13, 10, 29, 386, DateTimeKind.Local).AddTicks(3566),
                            DataValidade = new DateTime(2023, 12, 19, 2, 13, 59, 249, DateTimeKind.Local).AddTicks(4253),
                            Descricao = "Licensed Cotton Mouse",
                            FornecedorCnpj = "554849620001",
                            FornecedorCodigo = 1946,
                            FornecedorDescricao = "Greenholt, Kiehn and Kassulke",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "985171456412922",
                            DataFabricacao = new DateTime(2022, 11, 10, 22, 30, 43, 35, DateTimeKind.Local).AddTicks(9509),
                            DataValidade = new DateTime(2023, 6, 4, 13, 58, 19, 610, DateTimeKind.Local).AddTicks(8624),
                            Descricao = "Gorgeous Plastic Tuna",
                            FornecedorCnpj = "379374760001",
                            FornecedorCodigo = 1991,
                            FornecedorDescricao = "Wyman - Leuschke",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "696715446860857",
                            DataFabricacao = new DateTime(2022, 10, 28, 13, 12, 31, 253, DateTimeKind.Local).AddTicks(6448),
                            DataValidade = new DateTime(2023, 5, 20, 11, 22, 51, 554, DateTimeKind.Local).AddTicks(4707),
                            Descricao = "Gorgeous Concrete Soap",
                            FornecedorCnpj = "945186620001",
                            FornecedorCodigo = 853,
                            FornecedorDescricao = "Gottlieb - Jerde",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 13,
                            Codigo = "375049938376276",
                            DataFabricacao = new DateTime(2022, 9, 24, 20, 25, 14, 260, DateTimeKind.Local).AddTicks(6442),
                            DataValidade = new DateTime(2024, 2, 28, 20, 39, 25, 94, DateTimeKind.Local).AddTicks(5942),
                            Descricao = "Gorgeous Metal Gloves",
                            FornecedorCnpj = "503575450001",
                            FornecedorCodigo = 1619,
                            FornecedorDescricao = "Wolff, Dach and Mueller",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 14,
                            Codigo = "805232256046961",
                            DataFabricacao = new DateTime(2022, 12, 2, 8, 0, 39, 69, DateTimeKind.Local).AddTicks(5618),
                            DataValidade = new DateTime(2023, 12, 23, 16, 55, 13, 984, DateTimeKind.Local).AddTicks(1442),
                            Descricao = "Small Soft Shirt",
                            FornecedorCnpj = "644447810001",
                            FornecedorCodigo = 1959,
                            FornecedorDescricao = "Ondricka LLC",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 15,
                            Codigo = "983243423975842",
                            DataFabricacao = new DateTime(2022, 10, 11, 2, 4, 57, 391, DateTimeKind.Local).AddTicks(9160),
                            DataValidade = new DateTime(2023, 10, 26, 14, 48, 39, 116, DateTimeKind.Local).AddTicks(759),
                            Descricao = "Rustic Metal Ball",
                            FornecedorCnpj = "528908660001",
                            FornecedorCodigo = 775,
                            FornecedorDescricao = "Tillman Inc",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 16,
                            Codigo = "446136549049741",
                            DataFabricacao = new DateTime(2022, 9, 21, 2, 19, 13, 148, DateTimeKind.Local).AddTicks(9116),
                            DataValidade = new DateTime(2023, 8, 17, 2, 32, 58, 208, DateTimeKind.Local).AddTicks(117),
                            Descricao = "Incredible Steel Pants",
                            FornecedorCnpj = "183942750001",
                            FornecedorCodigo = 1602,
                            FornecedorDescricao = "Ruecker - Prosacco",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 17,
                            Codigo = "922903134313251",
                            DataFabricacao = new DateTime(2022, 9, 3, 21, 21, 8, 230, DateTimeKind.Local).AddTicks(7916),
                            DataValidade = new DateTime(2024, 2, 15, 6, 7, 15, 537, DateTimeKind.Local).AddTicks(4925),
                            Descricao = "Intelligent Rubber Shoes",
                            FornecedorCnpj = "043523910001",
                            FornecedorCodigo = 1632,
                            FornecedorDescricao = "Lowe and Sons",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 18,
                            Codigo = "148485161118768",
                            DataFabricacao = new DateTime(2023, 1, 29, 19, 18, 23, 945, DateTimeKind.Local).AddTicks(6189),
                            DataValidade = new DateTime(2024, 3, 9, 17, 13, 19, 459, DateTimeKind.Local).AddTicks(811),
                            Descricao = "Tasty Cotton Cheese",
                            FornecedorCnpj = "360498440001",
                            FornecedorCodigo = 1368,
                            FornecedorDescricao = "Considine, Lockman and Blanda",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 19,
                            Codigo = "628165242687026",
                            DataFabricacao = new DateTime(2023, 3, 31, 11, 12, 29, 178, DateTimeKind.Local).AddTicks(9698),
                            DataValidade = new DateTime(2023, 4, 25, 17, 4, 13, 829, DateTimeKind.Local).AddTicks(2244),
                            Descricao = "Intelligent Plastic Salad",
                            FornecedorCnpj = "913057710001",
                            FornecedorCodigo = 1259,
                            FornecedorDescricao = "Larkin, Ferry and O'Conner",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 20,
                            Codigo = "221559411559584",
                            DataFabricacao = new DateTime(2023, 2, 25, 19, 39, 20, 178, DateTimeKind.Local).AddTicks(1049),
                            DataValidade = new DateTime(2023, 6, 7, 13, 19, 55, 811, DateTimeKind.Local).AddTicks(9428),
                            Descricao = "Tasty Wooden Car",
                            FornecedorCnpj = "472762290001",
                            FornecedorCodigo = 414,
                            FornecedorDescricao = "Langosh LLC",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 21,
                            Codigo = "645597448016264",
                            DataFabricacao = new DateTime(2023, 3, 22, 11, 6, 43, 458, DateTimeKind.Local).AddTicks(3890),
                            DataValidade = new DateTime(2023, 12, 9, 13, 57, 51, 236, DateTimeKind.Local).AddTicks(6247),
                            Descricao = "Handmade Plastic Keyboard",
                            FornecedorCnpj = "367138110001",
                            FornecedorCodigo = 157,
                            FornecedorDescricao = "Homenick - Hane",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 22,
                            Codigo = "653436144215443",
                            DataFabricacao = new DateTime(2022, 10, 21, 20, 3, 30, 592, DateTimeKind.Local).AddTicks(2394),
                            DataValidade = new DateTime(2023, 12, 24, 15, 44, 43, 702, DateTimeKind.Local).AddTicks(5),
                            Descricao = "Ergonomic Plastic Table",
                            FornecedorCnpj = "992400800001",
                            FornecedorCodigo = 280,
                            FornecedorDescricao = "Cronin, Gusikowski and Corkery",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 23,
                            Codigo = "132129809681918",
                            DataFabricacao = new DateTime(2022, 12, 28, 8, 47, 38, 112, DateTimeKind.Local).AddTicks(6318),
                            DataValidade = new DateTime(2023, 11, 27, 9, 20, 36, 535, DateTimeKind.Local).AddTicks(843),
                            Descricao = "Fantastic Steel Shoes",
                            FornecedorCnpj = "699196190001",
                            FornecedorCodigo = 1583,
                            FornecedorDescricao = "Rohan - Kling",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 24,
                            Codigo = "091851133518442",
                            DataFabricacao = new DateTime(2022, 12, 3, 2, 2, 47, 384, DateTimeKind.Local).AddTicks(7617),
                            DataValidade = new DateTime(2023, 4, 19, 23, 39, 33, 293, DateTimeKind.Local).AddTicks(6053),
                            Descricao = "Practical Fresh Gloves",
                            FornecedorCnpj = "622048370001",
                            FornecedorCodigo = 1557,
                            FornecedorDescricao = "Bechtelar - Pollich",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 25,
                            Codigo = "207620778305909",
                            DataFabricacao = new DateTime(2023, 2, 18, 14, 38, 6, 597, DateTimeKind.Local).AddTicks(362),
                            DataValidade = new DateTime(2023, 9, 8, 0, 19, 51, 396, DateTimeKind.Local).AddTicks(7305),
                            Descricao = "Handcrafted Plastic Salad",
                            FornecedorCnpj = "302741550001",
                            FornecedorCodigo = 781,
                            FornecedorDescricao = "Raynor - Brekke",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 26,
                            Codigo = "550948906292759",
                            DataFabricacao = new DateTime(2023, 4, 2, 16, 1, 32, 649, DateTimeKind.Local).AddTicks(1301),
                            DataValidade = new DateTime(2023, 10, 22, 8, 31, 15, 106, DateTimeKind.Local).AddTicks(853),
                            Descricao = "Fantastic Soft Keyboard",
                            FornecedorCnpj = "334385280001",
                            FornecedorCodigo = 420,
                            FornecedorDescricao = "Robel and Sons",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 27,
                            Codigo = "998220673127968",
                            DataFabricacao = new DateTime(2023, 3, 21, 14, 15, 49, 11, DateTimeKind.Local).AddTicks(7492),
                            DataValidade = new DateTime(2024, 1, 1, 15, 42, 47, 319, DateTimeKind.Local).AddTicks(5649),
                            Descricao = "Ergonomic Frozen Ball",
                            FornecedorCnpj = "106478280001",
                            FornecedorCodigo = 290,
                            FornecedorDescricao = "Graham and Sons",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 28,
                            Codigo = "805339656882165",
                            DataFabricacao = new DateTime(2023, 1, 27, 22, 50, 3, 429, DateTimeKind.Local).AddTicks(3328),
                            DataValidade = new DateTime(2023, 9, 23, 21, 24, 30, 976, DateTimeKind.Local).AddTicks(7250),
                            Descricao = "Licensed Wooden Mouse",
                            FornecedorCnpj = "136489610001",
                            FornecedorCodigo = 1297,
                            FornecedorDescricao = "Moore, Gusikowski and Reilly",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 29,
                            Codigo = "155968346029034",
                            DataFabricacao = new DateTime(2022, 4, 23, 1, 16, 12, 416, DateTimeKind.Local).AddTicks(4694),
                            DataValidade = new DateTime(2023, 8, 20, 13, 32, 54, 359, DateTimeKind.Local).AddTicks(122),
                            Descricao = "Gorgeous Rubber Tuna",
                            FornecedorCnpj = "824026720001",
                            FornecedorCodigo = 158,
                            FornecedorDescricao = "McDermott - Cruickshank",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 30,
                            Codigo = "473210163901562",
                            DataFabricacao = new DateTime(2023, 4, 7, 14, 46, 17, 508, DateTimeKind.Local).AddTicks(1294),
                            DataValidade = new DateTime(2024, 1, 22, 1, 7, 14, 418, DateTimeKind.Local).AddTicks(7582),
                            Descricao = "Tasty Granite Pizza",
                            FornecedorCnpj = "996150640001",
                            FornecedorCodigo = 221,
                            FornecedorDescricao = "Kassulke LLC",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 31,
                            Codigo = "977490930012971",
                            DataFabricacao = new DateTime(2022, 9, 25, 9, 26, 37, 781, DateTimeKind.Local).AddTicks(4430),
                            DataValidade = new DateTime(2023, 12, 19, 17, 9, 34, 105, DateTimeKind.Local).AddTicks(3467),
                            Descricao = "Fantastic Rubber Shirt",
                            FornecedorCnpj = "029312350001",
                            FornecedorCodigo = 1915,
                            FornecedorDescricao = "Homenick, Bernier and Bartoletti",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 32,
                            Codigo = "581381521825612",
                            DataFabricacao = new DateTime(2022, 5, 1, 13, 29, 24, 316, DateTimeKind.Local).AddTicks(1022),
                            DataValidade = new DateTime(2023, 12, 19, 0, 13, 21, 560, DateTimeKind.Local).AddTicks(1131),
                            Descricao = "Rustic Steel Ball",
                            FornecedorCnpj = "802865890001",
                            FornecedorCodigo = 1210,
                            FornecedorDescricao = "Armstrong, Cremin and Beer",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 33,
                            Codigo = "694472358108958",
                            DataFabricacao = new DateTime(2022, 8, 6, 16, 12, 29, 863, DateTimeKind.Local).AddTicks(965),
                            DataValidade = new DateTime(2023, 10, 21, 18, 8, 31, 916, DateTimeKind.Local).AddTicks(7042),
                            Descricao = "Incredible Plastic Fish",
                            FornecedorCnpj = "489868780001",
                            FornecedorCodigo = 406,
                            FornecedorDescricao = "Stamm LLC",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 34,
                            Codigo = "272887419990022",
                            DataFabricacao = new DateTime(2022, 5, 9, 12, 24, 6, 584, DateTimeKind.Local).AddTicks(9777),
                            DataValidade = new DateTime(2023, 6, 19, 23, 39, 6, 872, DateTimeKind.Local).AddTicks(4002),
                            Descricao = "Licensed Concrete Hat",
                            FornecedorCnpj = "422636640001",
                            FornecedorCodigo = 987,
                            FornecedorDescricao = "Pacocha, Prosacco and Larson",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 35,
                            Codigo = "482994298331710",
                            DataFabricacao = new DateTime(2022, 7, 15, 0, 58, 14, 168, DateTimeKind.Local).AddTicks(5945),
                            DataValidade = new DateTime(2023, 9, 14, 21, 52, 38, 342, DateTimeKind.Local).AddTicks(6482),
                            Descricao = "Unbranded Wooden Chips",
                            FornecedorCnpj = "701364470001",
                            FornecedorCodigo = 1,
                            FornecedorDescricao = "Bailey - Borer",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 36,
                            Codigo = "314183846840490",
                            DataFabricacao = new DateTime(2022, 5, 7, 18, 4, 11, 956, DateTimeKind.Local).AddTicks(8837),
                            DataValidade = new DateTime(2024, 1, 27, 19, 48, 29, 797, DateTimeKind.Local).AddTicks(3509),
                            Descricao = "Handcrafted Frozen Chair",
                            FornecedorCnpj = "678292030001",
                            FornecedorCodigo = 588,
                            FornecedorDescricao = "Huel Group",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 37,
                            Codigo = "271133154842485",
                            DataFabricacao = new DateTime(2022, 9, 1, 2, 11, 39, 344, DateTimeKind.Local).AddTicks(1743),
                            DataValidade = new DateTime(2023, 12, 11, 2, 12, 41, 429, DateTimeKind.Local).AddTicks(1897),
                            Descricao = "Rustic Plastic Bike",
                            FornecedorCnpj = "514759940001",
                            FornecedorCodigo = 593,
                            FornecedorDescricao = "Abshire, Gorczany and Torp",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 38,
                            Codigo = "700672106108231",
                            DataFabricacao = new DateTime(2022, 5, 16, 11, 54, 41, 579, DateTimeKind.Local).AddTicks(2228),
                            DataValidade = new DateTime(2023, 5, 22, 5, 36, 34, 386, DateTimeKind.Local).AddTicks(2298),
                            Descricao = "Intelligent Wooden Car",
                            FornecedorCnpj = "224343820001",
                            FornecedorCodigo = 1280,
                            FornecedorDescricao = "Waelchi - Quitzon",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 39,
                            Codigo = "104949442042635",
                            DataFabricacao = new DateTime(2022, 10, 11, 23, 31, 38, 930, DateTimeKind.Local).AddTicks(802),
                            DataValidade = new DateTime(2024, 1, 1, 21, 24, 20, 320, DateTimeKind.Local).AddTicks(223),
                            Descricao = "Practical Fresh Table",
                            FornecedorCnpj = "366389770001",
                            FornecedorCodigo = 534,
                            FornecedorDescricao = "Heathcote - Abshire",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 40,
                            Codigo = "818361095892948",
                            DataFabricacao = new DateTime(2022, 9, 3, 22, 36, 39, 296, DateTimeKind.Local).AddTicks(8297),
                            DataValidade = new DateTime(2023, 9, 13, 22, 41, 45, 834, DateTimeKind.Local).AddTicks(5689),
                            Descricao = "Fantastic Cotton Towels",
                            FornecedorCnpj = "991607580001",
                            FornecedorCodigo = 53,
                            FornecedorDescricao = "Fritsch - Osinski",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 41,
                            Codigo = "184252861060826",
                            DataFabricacao = new DateTime(2023, 3, 16, 2, 33, 20, 949, DateTimeKind.Local).AddTicks(4513),
                            DataValidade = new DateTime(2023, 10, 22, 6, 18, 17, 225, DateTimeKind.Local).AddTicks(7042),
                            Descricao = "Handmade Steel Tuna",
                            FornecedorCnpj = "959964430001",
                            FornecedorCodigo = 501,
                            FornecedorDescricao = "Hartmann Group",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 42,
                            Codigo = "386410882193536",
                            DataFabricacao = new DateTime(2022, 11, 11, 11, 51, 4, 504, DateTimeKind.Local).AddTicks(5529),
                            DataValidade = new DateTime(2023, 8, 26, 18, 55, 0, 324, DateTimeKind.Local).AddTicks(4802),
                            Descricao = "Licensed Cotton Gloves",
                            FornecedorCnpj = "864618160001",
                            FornecedorCodigo = 151,
                            FornecedorDescricao = "Walter Group",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 43,
                            Codigo = "676906365516643",
                            DataFabricacao = new DateTime(2022, 5, 17, 12, 21, 46, 772, DateTimeKind.Local).AddTicks(4202),
                            DataValidade = new DateTime(2023, 9, 1, 21, 28, 0, 811, DateTimeKind.Local).AddTicks(479),
                            Descricao = "Gorgeous Granite Towels",
                            FornecedorCnpj = "748578490001",
                            FornecedorCodigo = 25,
                            FornecedorDescricao = "Donnelly, Herman and Rogahn",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 44,
                            Codigo = "063047019565214",
                            DataFabricacao = new DateTime(2023, 2, 11, 14, 42, 55, 33, DateTimeKind.Local).AddTicks(2383),
                            DataValidade = new DateTime(2023, 11, 20, 20, 16, 1, 976, DateTimeKind.Local).AddTicks(2213),
                            Descricao = "Handcrafted Concrete Mouse",
                            FornecedorCnpj = "382242630001",
                            FornecedorCodigo = 1223,
                            FornecedorDescricao = "Jones - Thompson",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 45,
                            Codigo = "196621333910438",
                            DataFabricacao = new DateTime(2022, 7, 6, 8, 46, 25, 736, DateTimeKind.Local).AddTicks(5490),
                            DataValidade = new DateTime(2024, 4, 2, 16, 17, 30, 695, DateTimeKind.Local).AddTicks(1866),
                            Descricao = "Fantastic Soft Gloves",
                            FornecedorCnpj = "743193290001",
                            FornecedorCodigo = 1163,
                            FornecedorDescricao = "Nader - Bernhard",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 46,
                            Codigo = "552225673869501",
                            DataFabricacao = new DateTime(2023, 3, 10, 5, 9, 56, 71, DateTimeKind.Local).AddTicks(364),
                            DataValidade = new DateTime(2023, 11, 20, 1, 8, 37, 703, DateTimeKind.Local).AddTicks(2469),
                            Descricao = "Rustic Wooden Towels",
                            FornecedorCnpj = "977010390001",
                            FornecedorCodigo = 497,
                            FornecedorDescricao = "Moen, Cronin and Kassulke",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 47,
                            Codigo = "733736356042640",
                            DataFabricacao = new DateTime(2023, 1, 14, 15, 9, 12, 22, DateTimeKind.Local).AddTicks(481),
                            DataValidade = new DateTime(2023, 6, 28, 19, 47, 17, 692, DateTimeKind.Local).AddTicks(7118),
                            Descricao = "Ergonomic Granite Chair",
                            FornecedorCnpj = "842981190001",
                            FornecedorCodigo = 402,
                            FornecedorDescricao = "Powlowski, Howe and Bailey",
                            Situacao = "Ativo"
                        },
                        new
                        {
                            Id = 48,
                            Codigo = "171533029412267",
                            DataFabricacao = new DateTime(2023, 2, 19, 12, 39, 32, 420, DateTimeKind.Local).AddTicks(4065),
                            DataValidade = new DateTime(2024, 2, 3, 17, 8, 58, 36, DateTimeKind.Local).AddTicks(9),
                            Descricao = "Tasty Soft Mouse",
                            FornecedorCnpj = "896488470001",
                            FornecedorCodigo = 11,
                            FornecedorDescricao = "Klein, Mills and Corwin",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 49,
                            Codigo = "598980603967494",
                            DataFabricacao = new DateTime(2022, 12, 22, 9, 57, 53, 673, DateTimeKind.Local).AddTicks(3091),
                            DataValidade = new DateTime(2024, 2, 4, 2, 18, 16, 867, DateTimeKind.Local).AddTicks(2171),
                            Descricao = "Sleek Wooden Cheese",
                            FornecedorCnpj = "364369610001",
                            FornecedorCodigo = 976,
                            FornecedorDescricao = "Steuber, O'Hara and VonRueden",
                            Situacao = "Inativo"
                        },
                        new
                        {
                            Id = 50,
                            Codigo = "709852972847087",
                            DataFabricacao = new DateTime(2023, 1, 10, 12, 3, 14, 295, DateTimeKind.Local).AddTicks(9736),
                            DataValidade = new DateTime(2023, 11, 24, 9, 9, 35, 517, DateTimeKind.Local).AddTicks(9796),
                            Descricao = "Incredible Soft Soap",
                            FornecedorCnpj = "763762020001",
                            FornecedorCodigo = 1579,
                            FornecedorDescricao = "Mraz LLC",
                            Situacao = "Ativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
